services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Limmy@jimmy3
      MYSQL_DATABASE: learning_hub_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./learning-hub-backend/backend
      dockerfile: ./Dockerfile.backend
    container_name: spring_backend
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/learning_hub_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD: Limmy@jimmy3
      - SERVER_PORT:8082

  frontend:
    build:
      context: ./learning-hub
      dockerfile: ./Dockerfile.frontend
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data: